backend:
  name: git-gateway
  branch: main # Branch to update (master by default)
media_folder: "static/uploads" # Media files will be stored in the static/uploads directory
public_folder: "/uploads" # URL to access uploaded media files

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
